### ISSUE TITLE
Language server download problem

### ISSUE THREAD

**Issue by baspinarenes** [zed-industries/community#1756]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I downloaded Zed and entered my workspace. The status bar was shown the download log of the typescript and json language servers. Then the "Checking for updates to TSX language server" log was shown and it's not progressing. When I look at the Zed's language folder, the contents of the folders are empty.

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

```
$ ls -la ~/Library/Application Support/Zed/languages/json-language-server
total 0
drwxr-xr-x@ 2 enes.baspinar  staff   64 Jul 13 08:30 .
drwxr-xr-x@ 6 enes.baspinar  staff  192 Jul 13 08:30 ..

$ ls -la ~/Library/Application Support/Zed/languages/typescript-language-server
total 0
drwxr-xr-x@ 2 enes.baspinar  staff   64 Jul 13 08:37 .
drwxr-xr-x@ 6 enes.baspinar  staff  192 Jul 13 08:30 ..
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/12035784/Zed.log)

**Comment by ForLoveOfCats** [comment]
Hey there 👋 If you delete `~/Library/Application Support/Zed/node` and restart the editor does the issue persist?

**Comment by fxsalazar** [comment]
Yes, it's still blocked at `Checking for updates to TSX language server`

**Comment by brandonweiss** [comment]
I’ve got the same problem with the JavaScript language server. It starts checking for updates and then hangs, making the language server unusable.

**Comment by jfrazier-eth** [comment]
I had this same issue. For anyone else that wants to use Zed while waiting for a fix - I was able to get around this issue by installing 0.93.4 ( [releases](https://zed.dev/releases/stable)). It installed the TS language server then auto updated to 0.95.3.

**Comment by ForLoveOfCats** [comment]
Hey folks 👋

Just a little update on where we're at with this, we've been able to reproduce the issue but only intermittently, and it always resolves upon restarting Zed. However it sounds like you've been having the issue persist through an editor restart which concerns me as that doesn't match my expectations of how our language server downloading mechanisms may fail.

Next time one of you encounters this issue can you *fully* quit (cmd-q) Zed, restart the editor, and then let us know if the issue persists. That will help me rule some stuff out and make sure we can know if our reproductions are even the same issue or not.

**Comment by joebno** [comment]
I have just run into this issue myself (Elixir Language Server) - it looped through the checking/downloading/checking cycle rapidly a few times, then stoped on checking.  

It did persist through several restarts.  I managed to clear it by:

1. Open a different project
2. Close the initial project
3. Fully quit Zed
4. Restart Zed
5. Open initial project
6. Close the other project

Of note is that I had the initial project and a file on the desktop open in the same instance.  It seems stable with just the initial project.

**Comment by andrejikonikov** [comment]
Guys to me it looks like a major issue with language servers download mechanism, same result with:
`Javascript language server`
`Typescript language server`
`Json language server`
all update checks/downloads get stuck, worst thing that `cmd-click` don't work with this...
tried versions 0.102.1, 0.96.2 with same sad results.

**Comment by JosephTLyons** [comment]
For the team, there is more information in these other closed issues:

- https://github.com/zed-industries/community/issues/1979
- https://github.com/zed-industries/community/issues/2050

**Comment by caleb654** [comment]
I was able to fix this issue running `sudo npm cache clean --force` according to [this Stack Overflow issue](https://stackoverflow.com/questions/59437833/error-your-cache-folder-contains-root-owned-files-due-to-a-bug-in-previous-ver). I was having problems specifically with the Typescript language server.

**Comment by adanselm** [comment]
> I was able to fix this issue running `sudo npm cache clean --force` according to [this Stack Overflow issue](https://stackoverflow.com/questions/59437833/error-your-cache-folder-contains-root-owned-files-due-to-a-bug-in-previous-ver). I was having problems specifically with the Typescript language server.

Made no difference for me with ElixirLS unfortunately ☹️

**Comment by JFOC** [comment]
> I was able to fix this issue running `sudo npm cache clean --force` according to [this Stack Overflow issue](https://stackoverflow.com/questions/59437833/error-your-cache-folder-contains-root-owned-files-due-to-a-bug-in-previous-ver). I was having problems specifically with the Typescript language server.

not working here still had an issue with JS and PHP

**Comment by nikolubbe** [comment]
I got around this for typescript by manually cloning and building the typescript-language-server repo:

1. Quit Zed completely
2. Delete `~/Library/Application\ Support/Zed/languages/typescript-language-server`
3. `git clone git@github.com:typescript-language-server/typescript-language-server.git ~/Library/Application\ Support/Zed/languages/typescript-language-server`
4. *`cd ~/Library/Application\ Support/Zed/languages/typescript-language-server && rm yarn.lock && yarn && yarn build` 
5. Start Zed

\* In 4 I delete the `yarn.lock` file because yarn wouldn't install with the repo's lockfile 🤷

**Comment by manurana** [comment]
I will add a python issue to the mix too :)
Zed 0.104.4 

The status message is stuck between
<img width="348" alt="image" src="https://github.com/zed-industries/community/assets/1749522/d55609b6-d028-454c-b2b4-055f7582a6c8">
and
<img width="367" alt="image" src="https://github.com/zed-industries/community/assets/1749522/06e905de-12c2-4b3d-ab16-a9515bc4a10b">


<details>

<summary>Log here</summary>

```ruby
2023-09-22T11:44:57 [INFO] starting language server "pyright", path: "/Users/manu/developer/knab/@old/las_2.0_kredit_manager", id: 1731
2023-09-22T11:44:57 [INFO] Node runtime install_if_needed
2023-09-22T11:44:58 [INFO] Node runtime install_if_needed
2023-09-22T11:44:59 [INFO] Node runtime install_if_needed
2023-09-22T11:44:59 [ERROR] invalid LSP message header ""
2023-09-22T11:44:59 [ERROR] failed to start language server "pyright": oneshot canceled
2023-09-22T11:44:59 [ERROR] server shut down
2023-09-22T11:44:59 [ERROR] Broken pipe (os error 32)
2023-09-22T11:44:59 [ERROR] missing executable in directory "/Users/manu/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2023-09-22T11:44:59 [INFO] About to spawn test binary
2023-09-22T11:44:59 [WARN] test binary failed to launch
2023-09-22T11:44:59 [WARN] test binary check failed
2023-09-22T11:44:59 [INFO] beginning to reinstall server
2023-09-22T11:44:59 [INFO] deleting server container
2023-09-22T11:44:59 [INFO] starting language server "pyright", path: "/Users/manu/developer/knab/@old/las_2.0_kredit_manager", id: 1732
2023-09-22T11:44:59 [INFO] Node runtime install_if_needed
2023-09-22T11:45:00 [INFO] Node runtime install_if_needed
2023-09-22T11:45:00 [INFO] Node runtime install_if_needed
2023-09-22T11:45:01 [ERROR] invalid LSP message header ""
2023-09-22T11:45:01 [ERROR] failed to start language server "pyright": oneshot canceled
2023-09-22T11:45:01 [ERROR] Broken pipe (os error 32)
2023-09-22T11:45:01 [ERROR] server shut down
2023-09-22T11:45:01 [ERROR] missing executable in directory "/Users/manu/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2023-09-22T11:45:01 [INFO] About to spawn test binary
2023-09-22T11:45:01 [WARN] test binary failed to launch
2023-09-22T11:45:01 [WARN] test binary check failed
2023-09-22T11:45:01 [INFO] beginning to reinstall server
2023-09-22T11:45:01 [INFO] deleting server container
2023-09-22T11:45:01 [INFO] starting language server "pyright", path: "/Users/manu/developer/knab/@old/las_2.0_kredit_manager", id: 1733
2023-09-22T11:45:01 [INFO] Node runtime install_if_needed

```

</details>

**Comment by nikolubbe** [comment]
> I will add a python issue to the mix too :) Zed 0.104.4

@manurana  This workaround (as mentioned above for TS and JSON) worked for me:
1. Quit Zed completely
2. Delete `~/Library/Application\ Support/Zed/languages/pyright`
3. `git clone git@github.com:microsoft/pyright.git ~/Library/Application\ Support/Zed/languages/pyright`
4. `cd ~/Library/Application\ Support/Zed/languages/pyright && npm install`
5. Start Zed

It looks like when Zed goes into this "Downloading / Checking for updates" loop, it keeps deleting the language folder in question and then recreating it (which is why you need to quit Zed completely before manually installing the LSPs)

**Comment by manurana** [comment]
Gracias, @nikolubbe 
That worked for me!

**Comment by ForLoveOfCats** [comment]
To give an update on this issue, we've been able to figure out that in this specific situation we're stuck in a loop installing the language server, getting a significantly fatal error on attempting to launch it, launching a test executable to see if the server install is borked, that fails to launch too, we clear the installation folder, and attempt again.

We don't know why this is happening, it doesn't seem to be restricted to any singular language server, or even kind of language server. All of the language servers we've seen issues with work fine for countless other folks so we know that the installation process for all these do work, and the process of installation for most is a simple as a download and unpack or an npm invocation so there's not a lot to go wrong there anyway.

As such we've yet to figure out *why* we're consistently getting borked copies of these servers on some folks' systems. Some permissions error, drive corruption, or what we don't know. It's been very frustrating to figure out and it pains me that we haven't been able to resolve it properly yet.

I hope this can give a bit of insight into where we're at right now with this issue

**Comment by manurana** [comment]
Hi @ForLoveOfCats , thanks for the update.
This is very interesting
On my machine, I first had this error with the typescript language server. This got resolved in one of the version updates. Then had the same issue with python.
OTOH, I have multiple other language servers (json, eslint, yaml) which did not have the issue

Let me know if I can help in any debugging.

**Comment by 4rc0s** [comment]
> I will add a python issue to the mix too :) Zed 0.104.4
> 
> The status message is stuck between <img alt="image" width="348" src="https://user-images.githubusercontent.com/1749522/269928795-d55609b6-d028-454c-b2b4-055f7582a6c8.png"> and <img alt="image" width="367" src="https://user-images.githubusercontent.com/1749522/269928952-06e905de-12c2-4b3d-ab16-a9515bc4a10b.png">
> 
> Log here

Same issue here with Python on MacOS.

**Comment by kevinschweikert** [comment]
Just to add some information. The Elixir Server now fails with:

```
Language server error: Elixir

error deserializing latest release
```

**Comment by kevinschweikert** [comment]
I finally fixed it for me by switching back from `rtx` to `asdf`!

**Comment by adanselm** [comment]
> I finally fixed it for me by switching back from `rtx` to `asdf`!

What versions of Elixir/Erlang do you have in your `asdf current` ?

**Comment by kevinschweikert** [comment]
Pretty up to date 

```shell
$ asdf current
elixir          1.15.6-otp-26  
erlang          26.1           

```

**Comment by 4rc0s** [comment]
@nikolubbe Thanks very much for sharing the workaround. I tried to get the JSON language server working on MacOS but am getting this error during the build script:

```

~/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-json-languageserver ~/Library/Application Support/Zed/languages/json-language-server
> pkg@5.8.0
node:internal/child_process:421
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at fabricate (/Users/foo/Library/Application Support/Zed/languages/json-language-server/node_modules/pkg/lib-es5/fabricator.js:55:51)
    at fabricateTwice (/Users/foo/Library/Application Support/Zed/languages/json-language-server/node_modules/pkg/lib-es5/fabricator.js:120:5)
    at MultiStream._queue (/Users/foo/Library/Application Support/Zed/languages/json-language-server/node_modules/pkg/lib-es5/producer.js:266:68)
    at MultiStream._next (/Users/foo/Library/Application Support/Zed/languages/json-language-server/node_modules/multistream/index.js:86:12)
    at Meter.onEnd (/Users/foo/Library/Application Support/Zed/languages/json-language-server/node_modules/multistream/index.js:129:12)
    at Object.onceWrapper (node:events:628:28)
    at Meter.emit (node:events:514:28)
    at endReadableNT (node:internal/streams/readable:1376:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

Node.js v20.7.0

```

**Comment by pehagg** [comment]
New user here. I downloaded the latest version (0.106.2) today and the CPU fans are having a field day with downloading the TSX language server in an endless loop. MacOS 14.0 (Sonoma), Mac mini 2018, 3,2 GHz 6-Core Intel Core i7. Looks like a promising editor, but as such completely unusable.

**Comment by joeypaak** [comment]
> 1. Quit Zed completely
> 2. Delete `~/Library/Application\ Support/Zed/languages/pyright`
> 3. `git clone git@github.com:microsoft/pyright.git ~/Library/Application\ Support/Zed/languages/pyright`
> 4. `cd ~/Library/Application\ Support/Zed/languages/pyright && npm install`
> 5. Start Zed
> 
> It looks like when Zed goes into this "Downloading / Checking for updates" loop, it keeps deleting the language folder in question and then recreating it (which is why you need to quit Zed completely before manually installing the LSPs)

@nikolubbe I was getting nuts and was about to create an issue but found this already existing and your method really helped. Thx 😭

**Comment by redeemefy** [comment]
To add more context into my case. I installed my nodes version with Volta.

**Comment by RenzoDas** [comment]
> To add more context into my case. I installed my nodes version with Volta.

* This is also my case, and @nikolubbe solution is not working for me.

**Comment by jdupas22** [comment]
Hey! Still getting this issue on every language server I tried (Javascript, Python), I'm on macOS Sonoma 14.1 beta. None of the fixes mentioned in this issue solved it for me.

**Comment by redeemefy** [comment]
Could it be that the type of MacBook matters? My teammate has the new MacBook with M1/2 CPU and I have a 2019 with Intel and he doesn't have the infinite loop of installing language servers.

**Comment by manurana** [comment]
Reporting back to add data points
The latest update (0.107.6) brought back this bug for me on the Typescript language server. Does not go away with the manual install suggestion
The previously reported bug with the Python language server (which was resolved by the manual install) remains resolved for now

macOS Sonoma
Apple M1 chip
node 18.17.1 using nvm

**Comment by sheckathorne** [comment]
> Could it be that the type of MacBook matters? My teammate has the new MacBook with M1/2 CPU and I have a 2019 with Intel and he doesn't have the infinite loop of installing language servers.

FWIW I have a MBP M1 and having the issue for both HTML and YAML language servers

**Comment by danilotorrisi** [comment]
I'm also stuck with this issue, I would love to try out zed but I haven't find a way to exit the loop.

I'm also with a MBP M1, macOS Sonoma 14.0, node 20 on nvm

**Comment by caner-cetin** [comment]
Same issue persists, and none of the comments helped. Tried to manually install pyright over and over again, no luck. Still stuck on same loop.
```bash
                    'c.          canercetin@caners-MacBook-Pro.local 
                 ,xNMM.          ----------------------------------- 
               .OMMMMo           OS: macOS 13.3 22E252 arm64 
               OMMM0,            Host: Mac14,7 
     .;loddo:' loolloddol;.      Kernel: 22.4.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 5 days, 21 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (port), 206 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: kitty 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M2 
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M2 
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1985MiB / 16384MiB 
       .cooc,.    .,coo:.
                                                                                                             
```
```bash
└> node --version
v21.1.0
```

**Comment by 11bit** [comment]
I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zod was installing everything there instead of `~/Library/Application Support/Zed`. 

I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

**Comment by caner-cetin** [comment]
I love you! That worked for me @11bit

**Comment by redeemefy** [comment]
> I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zed was installing everything there instead of `~/Library/Application Support/Zed`.
> 
> I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

This worked for me.

**Comment by sheckathorne** [comment]
Thanks @11bit, this worked for me also

**Comment by tcrammond** [comment]
Combining both manual install of the language server https://github.com/zed-industries/community/issues/1756#issuecomment-1731087612 and deleting `package.json` in the home directory worked for me on version 0.110.2. Thanks!

**Comment by Spikeysanju** [comment]
> I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zed was installing everything there instead of `~/Library/Application Support/Zed`.
> 
> I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

This worked for me. Thanks @11bit

**Comment by TwanLuttik** [comment]
> I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zed was installing everything there instead of `~/Library/Application Support/Zed`.
> 
> I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

Thank you so much @11bit, this solved my issue right away

**Comment by jamescary** [comment]
> I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zed was installing everything there instead of `~/Library/Application Support/Zed`.
> 
> I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

This also worked for me. Thanks @11bit!

**Comment by DarthMarino** [comment]
Try updating to the latest stable release they just released today (v0.111.6). The issue seems to be fixed

**Comment by ForLoveOfCats** [comment]
As much as I wish we had, we haven't fixed anything in the past few releases. In `0.111.4` we did change some things so that this won't go on endlessly, but on systems where a particular language server is failing to install it will still fail to install.

I am personally looking into what might cause our downloaded copy of NPM to install Node based language servers into the home directory which is what quite a few folks in this thread have reported happening.

Our new understanding of the situation is that there's nothing "broken" about our mechanisms for installing these failing servers. Trying to find some bug in that code is why we've spent so much time spinning our tires. What we think now is that individual servers have specific configuration issues on some systems which all result in failures which look the same from how Zed reacts. A few weeks ago we shipped some logging improvements which should allow us to track down individual failures a bit better.

We're in the middle of a big UI library rewrite which impacts a lot of internal systems so we have been slower to respond than usual but that should wrap up sometime soonish. We're also going Open Source soon™️ and I hope folks will be able to discover these configuration failures on their systems and help us figure out how to get affected servers running :)

**Comment by marcotterra** [comment]
> I had the same issue and I found that for some reason I have a `package.json` in my home directory, so probably Zed was installing everything there instead of `~/Library/Application Support/Zed`.
> 
> I closed Zed and deleted everything from my home dir (~/package.json, ~/package.lock.json, ~/node_modules/) and everything works!

Thank you so much @11bit!
